# Generated by Django 5.1.1 on 2024-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_des', models.TextField(null=True)),
                ('recipe_img', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
